---
- name: Check if a directory f1 is present if not create a file f1
  hosts: all
  tasks:
    - name: Check for f1 directory
      stat:
        path: /home/ubuntu/f1
      register: a
    - name: Display output of the above module
      debug:
        var: a
    - name: Create file if folder f1 is not present
      file:
        name: /home/ubuntu/f1
        state: touch
      when: a.stat.exists == false
